events {}

http {
    upstream client_server_backend {
        server client_server1:8000;
    }

    upstream social_content_backend {
        server social_content_gate1:8000;
    }

    upstream pgadmin_ui {
        server pgadmin:5050;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://client_server_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_redirect off;
        }

        location /social/ {
            proxy_pass http://social_content_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_redirect off;
        }
    }
}